export const CRYPTO_ASSET_NAMES: Record<string, string> = {
    // Top Market Cap Assets
    'BTC': 'Bitcoin',
    'ETH': 'Ethereum',
    'XRP': 'Ripple',
    'SOL': 'Solana',
    'ADA': 'Cardano',
    'DOT': 'Polkadot',
    'DOGE': 'Dogecoin',
    'AVAX': 'Avalanche',
    'MATIC': 'Polygon',
    'LINK': 'Chainlink',
    'ATOM': 'Cosmos',
    'UNI': 'Uniswap',
    'LTC': 'Litecoin',
    'ALGO': 'Algorand',
    'NEAR': 'Near Protocol',
    'QNT': 'Quant',
    'FIL': 'Filecoin',
    'TRX': 'Tron',
    'XLM': 'Stellar',
    'USDT': 'Tether',
    'USDC': 'USD Coin',
    'BCH': 'Bitcoin Cash',
    'VET': 'VeChain',
    'ICP': 'Internet Computer',
    'MANA': 'Decentraland',
    'HBAR': 'Hedera',
    'XTZ': 'Tezos',
    'THETA': 'Theta Network',
    'AAVE': 'Aave',
    'EOS': 'EOS',
    'CAKE': 'PancakeSwap',
    'AXS': 'Axie Infinity',
    'SAND': 'The Sandbox',
    'GRT': 'The Graph',
    'FTM': 'Fantom',
    'MKR': 'Maker',
    'SNX': 'Synthetix',
    'ZEC': 'Zcash',
    'DASH': 'Dash',
    'NEO': 'Neo',
    'COMP': 'Compound',
    'CHZ': 'Chiliz',
    'STX': 'Stacks',
    'CVX': 'Convex Finance',
    'LRC': 'Loopring',
    'ONE': 'Harmony',
    'HOT': 'Holo',
    'KSM': 'Kusama',
    'YFI': 'Yearn.finance',
    'BAT': 'Basic Attention Token',
    'SUSHI': 'SushiSwap',
    'ZRX': '0x',
    'ENJ': 'Enjin Coin',
    'ICX': 'ICON',
    'QTUM': 'Qtum',
    'OMG': 'OMG Network',
    'ZIL': 'Zilliqa',
    'ONT': 'Ontology',
    'IOST': 'IOST',
    'RVN': 'Ravencoin',
    'SXP': 'Swipe',
    'SC': 'Siacoin',
    'DGB': 'DigiByte',
    'ANKR': 'Ankr',
    'OCEAN': 'Ocean Protocol',
    '1INCH': '1inch',
    'REN': 'Ren',
    'CELO': 'Celo',
    'FET': 'Fetch.ai',
    'UMA': 'UMA',
    'KAVA': 'Kava',
    'BAND': 'Band Protocol',
    'IOTX': 'IoTeX',
    'RSR': 'Reserve Rights',
    'COTI': 'COTI',
    'CTSI': 'Cartesi',
    'STORJ': 'Storj',
    'OGN': 'Origin Protocol',
    'GLM': 'Golem',
    'GNO': 'Gnosis',
    'LPT': 'Livepeer',
    'SKL': 'Skale',
    'NKN': 'NKN',
    'OXT': 'Orchid',
    'POWR': 'Powerledger',
    'RLC': 'iExec RLC',
    'NMR': 'Numeraire',
    'TRB': 'Tellor',
    'BAL': 'Balancer',
    'BNT': 'Bancor',
    'SRM': 'Serum',
    'FIDA': 'Bonfida',
    'RAY': 'Raydium',
    'MNGO': 'Mango',
    'ORCA': 'Orca',
    'SABER': 'Saber',
    'MER': 'Mercurial',
    'SLND': 'Solend',
};
